# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1b51bc8f1760a95efb4103ce3b7997e5"
application_url = "https://hebrew-ai-search.duckdns.org"
embedded = true
name = "ai-search"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[app_proxy]
url = "https://hebrew-ai-search.duckdns.org/proxy/search"
prefix = "apps"
subpath = "search"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products"
  topics = [ "products/create", "products/update", "products/delete" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/bulk-operations"
  topics = [ "bulk_operations/finish" ]

[auth]
redirect_urls = [ "https://hebrew-ai-search.duckdns.org/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
